[build]
  command = "npm run build"
  publish = "dist"

# Redirect all traffic to HTTPS
[[redirects]]
  from = "http://wallzee.live/*"
  to = "https://wallzee.live/:splat"
  status = 301
  force = true

# Handle SPA routing - ensure all paths route to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: *.cloudfront.net *.githubusercontent.com; script-src 'self' 'unsafe-inline' *.googletagmanager.com; style-src 'self' 'unsafe-inline'; connect-src 'self' *.appwrite.io;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache settings for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
